import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet({"/product"})
public class ShowProduct extends HttpServlet {
   protected void service(HttpServletRequest var1, HttpServletResponse var2) throws ServletException, IOException {
      var2.setContentType("text/html");
      PrintWriter var3 = var2.getWriter();
      var3.print("<!DOCTYPE html><html><title>Window-Mart-Vintage Skinny Jeans</title><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1'><link rel='stylesheet' href='https://www.w3schools.com/w3css/4/w3.css'><link rel='icon' href='Capture.PNG'> <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Raleway'><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>");
      var3.print("<style>body,h1,h2,h3,h4,h5,h6 {font-family: 'Raleway', Arial, Helvetica, sans-serif}.mySlides {display: none}</style>");
      var3.print("<body class='w3-content w3-border-left w3-border-right'><!-- Sidebar/menu --><nav class='w3-sidebar w3-light-grey w3-collapse w3-top' style='z-index:3;width:260px' id='mySidebar'><div class='w3-container w3-display-container w3-padding-16'><i onclick='w3_close()' class='fa fa-remove w3-hide-large w3-button w3-transparent w3-display-topright'></i><h3>Best Prices</h3><h3>only $21</h3>");
      var3.print("</div><div class='w3-bar-block'><a href='#desc' class='w3-bar-item w3-button w3-padding-16'><i class='fa fa-building'></i> Description</a><a href='#reviews' class='w3-bar-item w3-button w3-padding-16'><i class='fa fa-users'></i> User Reviews</a><a href='#buy' class='w3-bar-item w3-button w3-padding-16'><i class='fa fa-dollar'></i> Buy Now</a></div></nav>");
      var3.print("<!-- Top menu on small screens --><header class='w3-bar w3-top w3-hide-large w3-black w3-xlarge'><span class='w3-bar-item'>More</span><a href='javascript:void(0)' class='w3-right w3-bar-item w3-button' onclick='w3_open()'><i class='fa fa-bars'></i></a></header>");
      var3.print("<!-- Overlay effect when opening sidebar on small screens --><div class='w3-overlay w3-hide-large' onclick='w3_close()' style='cursor:pointer' title='close side menu' id='myOverlay'></div>");
      var3.print("<!-- !PAGE CONTENT! --><div class='w3-main w3-white' style='margin-left:260px'>");
      var3.print("<!-- Push down content on small screens --><div class='w3-hide-large' style='margin-top:80px'></div><header class='w3-container w3-xlarge'><p class='w3-left'>Jeans</p><p class='w3-right'><a class='fa fa-shopping-cart w3-margin-right' href='cart.html' style='text-decoration: none;'></a><i class='fa fa-user-circle'></i></p></header>");
      var3.print("<!-- Slideshow Header --><div class='w3-container' id='images'><h2 class='w3-text-black'>Vintage Skinny Jeans</h2><div class='w3-display-container mySlides'><img src='img/jeans1.jpg' style='width:50%;margin-bottom:-6px'><div class='w3-display-bottomleft w3-container w3-black'><p>Front view</p></div></div><div class='w3-display-container mySlides'><img src='img/jeans1.jpg' style='width:50%;margin-bottom:-6px'><div class='w3-display-bottomleft w3-container w3-black'><p>Profile</p></div></div><div class='w3-display-container mySlides'><img src='img/jeans1.jpg' style='width:50%;margin-bottom:-6px'><div class='w3-display-bottomleft w3-container w3-black'><p>Rear View</p></div></div><div class='w3-display-container mySlides'><img src='img/jeans1.jpg' style='width:50%;margin-bottom:-6px'><div class='w3-display-bottomleft w3-container w3-black'>");
      var3.print("<p>The Brand</p></div></div></div>");
      var3.print("<div class='w3-row-padding w3-section'><div class='w3-col s3'><img class='demo w3-opacity w3-hover-opacity-off' src='img/jeans1.jpg' style='width:100%;cursor:pointer' onclick='currentDiv(1)' title='Front view'></div><div class='w3-col s3'><img class='demo w3-opacity w3-hover-opacity-off' src='img/jeans1.jpg' style='width:100%;cursor:pointer' onclick='currentDiv(2)' title='Profile'></div><div class='w3-col s3'><img class='demo w3-opacity w3-hover-opacity-off' src='img/jeans1.jpg' style='width:100%;cursor:pointer' onclick='currentDiv(3)' title='Rear view'></div><div class='w3-col s3'>");
      var3.print("<img class='demo w3-opacity w3-hover-opacity-off' src='img/jeans1.jpg' style='width:100%;cursor:pointer' onclick='currentDiv(4)' title='The Brand'></div></div>");
      var3.print("<div class='w3-container'><div id='desc'><h4><strong>Product Description</strong></h4><div class='w3-row w3-large'><div class='w3-col s6'><p><i class='fa fa-fw fa-male'></i> Available sizes: 4</p>");
      var3.print("</div><div class='w3-col s6'><p><i class='fa fa-fw fa-clock-o'></i> Hurry up! few left in stock</p></div><p>Super soft denim fabric with added stretchability and breathable fabric for all day comfort</p></div></div>");
      var3.print("<hr><div id=buy><button type='submit' class='w3-button w3-black w3-third' value='Buy'>Add to Cart</button></div><hr><hr><div id='reviews'><h4><strong>User Review</strong></h4><p>Wonderful product. great quality. Really pleased with my purchase.</p><p>Rating: <i class='fa fa-star'></i><i class='fa fa-star'></i><i class='fa fa-star'></i><i class='fa fa-star'></i><i class='fa fa-star-half-o'></i> </p><hr></div><h4><strong>Return Rules</strong></h4><p>Products can be returned upto 14 days after purchase. The product must be in original packaging without any damage (Excluding manufacturing defects)</p></div><hr>");
      var3.print("<!-- Contact --><footer class='w3-padding-64 w3-light-grey w3-small w3-center' id='footer'><div class='w3-row-padding'><div class='w3-col s4'><h4>Contact</h4><p>Questions? Go ahead.</p><form action='/action_page.php' target='_blank'><p><input class='w3-input w3-border' type='text' placeholder='Name' name='Name' required></p><p><input class='w3-input w3-border' type='text' placeholder='Email' name='Email' required></p><p><input class='w3-input w3-border' type='text' placeholder='Subject' name='Subject' required></p><p><input class='w3-input w3-border' type='text' placeholder='Message' name='Message' required></p><button type='submit' class='w3-button w3-block w3-black'>Send</button></form></div>");
      var3.print("<div class='w3-col s4'><h4>About</h4><p><a href='#'>About us</a></p><p><a href='#'>We're hiring</a></p><p><a href='#'>Support</a></p><p><a href='#'>Shipment</a></p><p><a href='#'>Payment</a></p><p><a href='#'>Gift card</a></p><p><a href='#'>Return</a></p><p><a href='#'>Help</a></p></div>");
      var3.print("<div class='w3-col s4 w3-justify'><h4>Store</h4><p><i class='fa fa-fw fa-map-marker'></i> Window-Mart</p><p><i class='fa fa-fw fa-phone'></i> 0044123123</p><p><i class='fa fa-fw fa-envelope'></i> sales@winmart.com</p><h4>We accept</h4>");
      var3.print("<p><i class='fa fa-fw fa-credit-card'></i> Credit Card</p><p><i class='fa fa-fw fa-dollar'></i> Cash on Delivery</p><br><i class='fa fa-facebook-official w3-hover-opacity w3-large'></i><i class='fa fa-instagram w3-hover-opacity w3-large'></i><i class='fa fa-snapchat w3-hover-opacity w3-large'></i><i class='fa fa-pinterest-p w3-hover-opacity w3-large'></i><i class='fa fa-twitter w3-hover-opacity w3-large'></i><i class='fa fa-linkedin w3-hover-opacity w3-large'></i></div></div></footer><!-- End page content --></div>");
      var3.print("<script>// Script to open and close sidebar when on tablets and phonesfunction w3_open() {document.getElementById('mySidebar').style.display = 'block';document.getElementById('myOverlay').style.display = 'block';}");
      var3.print("function w3_close() {document.getElementById('mySidebar').style.display = 'none';document.getElementById('myOverlay').style.display = 'none';}");
      var3.print("// Slideshow Apartment Imagesvar slideIndex = 1;showDivs(slideIndex);function plusDivs(n) {showDivs(slideIndex += n);}");
      var3.print("function currentDiv(n) {showDivs(slideIndex = n);}");
      var3.print("function showDivs(n) {var i;var x = document.getElementsByClassName('mySlides');var dots = document.getElementsByClassName('demo');if (n > x.length) {slideIndex = 1}if (n < 1) {slideIndex = x.length}for (i = 0; i < x.length; i++) {x[i].style.display = 'none';}for (i = 0; i < dots.length; i++) {dots[i].className = dots[i].className.replace(' w3-opacity-off', '');}x[slideIndex-1].style.display = 'block';dots[slideIndex-1].className += ' w3-opacity-off';}</script></body></html>");
      var3.close();
   }
}
